// 車両人員予定表：共有バックエンド v55
// イベント単位の差分保存＋削除トゥームストーンで、PC/スマホの古い全体データによる上書きを防止。
const SPREADSHEET_ID='1KYmKn-zGJyLdrut_pjQ_QFVWH6BCIR_wNu910Hf2i80';
const SHEET_NAME='予定表データ';
const LEGACY_SHEET_NAME='予定データ';
const CHUNK_SIZE=45000;
const CACHE_KEY='vehicle_schedule_state_v55';
const CACHE_TTL=21600;
function doGet(e){try{if(e&&e.parameter&&e.parameter.api==='1'){const state=readState_(true),cb=e.parameter.prefix||e.parameter.callback;if(cb)return jsonp_(cb,state);return json_(state)}if(e&&e.parameter&&e.parameter.health==='1')return json_({ok:true,spreadsheet:'connected'});return HtmlService.createHtmlOutputFromFile('index').setTitle('車両人員予定表').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}catch(err){return HtmlService.createHtmlOutput('<pre>起動エラー: '+String(err&&err.message||err).replace(/</g,'&lt;')+'</pre>')}}
function doPost(e){try{let raw=e&&e.parameter&&e.parameter.payload?e.parameter.payload:'';if(!raw&&e&&e.postData&&e.postData.contents)raw=e.postData.contents;if(!raw)return json_({ok:false,error:'payloadがありません'});return json_(writePatch_(JSON.parse(raw)))}catch(err){return json_({ok:false,error:String(err&&err.message||err)})}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function jsonp_(cb,o){if(!/^[A-Za-z_$][0-9A-Za-z_$]*$/.test(cb))return ContentService.createTextOutput('invalid callback');return ContentService.createTextOutput(cb+'('+JSON.stringify(o)+');').setMimeType(ContentService.MimeType.JAVASCRIPT)}
function defaultState_(){return{events:[],vehicles:[],people:[],logs:[],lastUpdated:0,revision:0,hasData:false,saveToken:'',deleted:{}}}
function getSpreadsheet_(){return SpreadsheetApp.openById(SPREADSHEET_ID)}
function getSheet_(){const ss=getSpreadsheet_();let sh=ss.getSheetByName(SHEET_NAME);if(!sh)sh=ss.insertSheet(SHEET_NAME);return sh}
function readRaw_(sh){const n=sh.getLastRow();if(!n)return'';return sh.getRange(1,1,n,1).getDisplayValues().map(r=>r[0]).join('')}
function normalize_(d){const x=d||{};const vehicles=Array.isArray(x.vehicles)?x.vehicles.map(v=>Array.isArray(v)?{id:String(v[0]||''),detail:String(v[1]||'2t'),memo:''}:{id:String(v&&v.id||''),detail:String(v&&v.detail||'2t'),memo:String(v&&v.memo||'')}).filter(v=>v.id):[];const people=Array.isArray(x.people)?x.people.map(p=>Array.isArray(p)?String(p[0]||''):String(p||'')).filter(Boolean):[];const events=Array.isArray(x.events)?x.events.map(e=>{const z=Object.assign({},e||{});if(!Array.isArray(z.vehicles))z.vehicles=z.vehicle?[z.vehicle]:[];if(!Array.isArray(z.people))z.people=z.person?[z.person]:[];if(!z.vehicle)z.vehicle=z.vehicles[0]||'';if(!z.person)z.person=z.people[0]||'';if(!z.kind&&z.status)z.kind=z.status==='確定'?'confirmed':'plan';if(z.kind==='work')z.kind='confirmed';if(!z.start)z.start='08:00';if(!z.end)z.end='16:00';if(!z.endDate)z.endDate=z.date||'';z.updatedAt=Number(z.updatedAt||0);z.updatedBy=String(z.updatedBy||'');return z}):[];return{events,vehicles,people,logs:Array.isArray(x.logs)?x.logs:[],lastUpdated:Number(x.lastUpdated||0),revision:Number(x.revision||0),hasData:false,saveToken:String(x.saveToken||''),deleted:x.deleted&&typeof x.deleted==='object'?x.deleted:{}}}
function readState_(forceFresh){const ss=getSpreadsheet_(),sh=getSheet_();let raw=readRaw_(sh);if(!raw){const old=ss.getSheetByName(LEGACY_SHEET_NAME);if(old)raw=readRaw_(old)}if(!raw)return defaultState_();try{const s=normalize_(JSON.parse(raw));s.hasData=!!(s.events.length||s.vehicles.length||s.people.length);return s}catch(err){return defaultState_()}}
function newer_(a,b){const at=Number(a&&a.updatedAt||0),bt=Number(b&&b.updatedAt||0);if(at!==bt)return at>bt;return String(a&&a.updatedBy||'')>String(b&&b.updatedBy||'')}
function writePatch_(data){const lock=LockService.getScriptLock();lock.waitLock(20000);try{const current=readState_(true),now=Date.now(),events=new Map(current.events.map(e=>[String(e.id),e])),deleted=Object.assign({},current.deleted||{});const changes=Array.isArray(data.changes)?data.changes:[];changes.forEach(incoming=>{const id=String(incoming.id);const tomb=deleted[id];if(tomb&&Number(tomb.updatedAt||0)>=Number(incoming.updatedAt||0))return;const old=events.get(id);if(!old||newer_(incoming,old)){events.set(id,normalize_({events:[incoming]}).events[0]);delete deleted[id]}});const dels=data.deletes&&typeof data.deletes==='object'?data.deletes:{};Object.keys(dels).forEach(id=>{const t=dels[id]||{};const ts=Number(t.updatedAt||0);const old=events.get(id),oldT=deleted[id];if((!old||ts>=Number(old.updatedAt||0))&&(!oldT||ts>=Number(oldT.updatedAt||0))){events.delete(id);deleted[id]={updatedAt:ts,updatedBy:String(t.updatedBy||data.clientId||'')}}});let vehicles=current.vehicles,people=current.people;if(Number(data.masterUpdatedAt||0)>Number(current.masterUpdatedAt||0)){if(Array.isArray(data.vehicles)&&data.vehicles.length)vehicles=data.vehicles;if(Array.isArray(data.people)&&data.people.length)people=data.people}const next={events:[...events.values()],vehicles,people,logs:current.logs,lastUpdated:now,revision:Number(current.revision||0)+1,hasData:true,saveToken:String(data.saveToken||''),deleted,masterUpdatedAt:Math.max(Number(current.masterUpdatedAt||0),Number(data.masterUpdatedAt||0))};const raw=JSON.stringify(next),sh=getSheet_();sh.getRange(1,1,Math.max(sh.getMaxRows(),1),1).clearContent();const rows=[];for(let i=0;i<raw.length;i+=CHUNK_SIZE)rows.push([raw.slice(i,i+CHUNK_SIZE)]);sh.getRange(1,1,rows.length,1).setValues(rows);return{ok:true,lastUpdated:next.lastUpdated,revision:next.revision,hasData:true,saveToken:next.saveToken,eventCount:next.events.length,vehicleCount:next.vehicles.length,peopleCount:next.people.length}}finally{lock.releaseLock()}}
function getSharedState(){return readState_(true)}
function saveSharedState(data){try{return writePatch_(data||{})}catch(err){return{ok:false,error:String(err&&err.message||err)}}}
